# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vogl_g_w.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow
from PyQt5.QtGui import QPixmap
from PyQt5.QtCore import Qt

import vogl_game
from vogl_game import *

image = 'pictures/pepe_bear (2).png'
white_color = 'background-color:white; border-radius:5px'


class Ui_vogl_g_w(QMainWindow):

    def __init__(self):
        super().__init__()
        self.setObjectName("vogl_g_w")
        self.resize(800, 600)
        self.centralwidget = QMainWindow(self)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 30, 701, 451))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.restartButton = QtWidgets.QPushButton(self.centralwidget)
        self.restartButton.setGeometry(QtCore.QRect(40, 500, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.restartButton.setFont(font)
        self.restartButton.setObjectName("restartButton")
        self.exitButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitButton.setGeometry(QtCore.QRect(550, 500, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.exitButton.setFont(font)
        self.exitButton.setObjectName("exitButton")
        self.setCentralWidget(self.centralwidget)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def get_layout(self):
        return self.gridLayout

    def retranslateUi(self, vogl_g_w):
        _translate = QtCore.QCoreApplication.translate
        vogl_g_w.setWindowTitle(_translate("vogl_g_w", "GameWindow"))
        self.restartButton.setText(_translate("vogl_g_w", "Restart"))
        self.exitButton.setText(_translate("vogl_g_w", "Exit"))
