# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vogl.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow
from PyQt5.QtCore import Qt

path = 'levels'


class Ui_MainWindow(QMainWindow):

    def __init__(self):
        super().__init__()
        self.setObjectName("MainWindow")
        self.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.setFont(font)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")

        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(300, 360, 181, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.startButton.setFont(font)
        self.startButton.setObjectName("startButton")

        self.levelsBox = QtWidgets.QComboBox(self.centralwidget)
        self.levelsBox.setGeometry(QtCore.QRect(320, 130, 131, 31))
        self.levelsBox.setObjectName("levelsBox")

        self.level_label = QtWidgets.QLabel(self.centralwidget)
        self.level_label.setGeometry(QtCore.QRect(330, 80, 171, 31))
        self.level_label.setObjectName("level_label")

        self.selectedLevel = QtWidgets.QLabel(self.centralwidget)
        self.selectedLevel.setGeometry(QtCore.QRect(330, 210, 151, 17))
        self.selectedLevel.setObjectName("selectedLevel")

        self.levelLine = QtWidgets.QLineEdit(self.centralwidget)
        self.levelLine.setGeometry(QtCore.QRect(330, 260, 113, 25))
        self.levelLine.setAlignment(QtCore.Qt.AlignCenter)
        self.levelLine.setObjectName("levelLine")

        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        self.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.level_label.setText(_translate("MainWindow", "Choose level"))

